### ISSUE TITLE
npm run build is throwing error for vue application.

### ISSUE THREAD

**Issue by ashutoshSce** [jualoppaz/single-spa-auth-app#8]
[BABEL] single-spa-auth-app/src/singleSpaEntry.js: No "exports" main resolved in single-spa-auth-app/node_modules/@babel/helper-compilation-targets/package.json (While processing: "single-spa-auth-app/node_modules/@vue/cli-plugin-babel/preset.js")

m i missing something?

**Comment by jualoppaz** [comment]
Hi @ashutoshSce ! Thank you so much for reporting this error!

After a quick view I could see this issue: https://github.com/babel/babel/issues/11216 . This error is produced by new node versions in its way of exporting modules, as you can see in referenced issue in https://github.com/nodejs/node/issues/32107.

However, there is a quick fix for this which consist on update package-lock.json file with all tree dependencies updated. I have just fix this error in new [v0.1.3 version](https://github.com/jualoppaz/single-spa-auth-app/releases/tag/v0.1.3). Updating package-lock.json file updated also @babel/helper-compilation-targets version as you can see [here](https://github.com/jualoppaz/single-spa-auth-app/commit/30e432a1567cd0c7b57220f70fde8ec308d0f372#diff-32607347f8126e6534ebc7ebaec4853d).

With this fix this error may dissappear ;)
